CREATE INDEX idx_nguoi_dung_ma_vai_tro ON nguoi_dung(ma_vai_tro);
CREATE INDEX idx_ca_lam_viec_ma_thu_ngan ON ca_lam_viec(ma_thu_ngan);
CREATE INDEX idx_san_pham_ma_danh_muc ON san_pham(ma_danh_muc);
CREATE INDEX idx_bien_the_san_pham_ma_san_pham ON bien_the_san_pham(ma_san_pham);
CREATE INDEX idx_gio_hang_ma_khach_hang ON gio_hang(ma_khach_hang);
CREATE INDEX idx_gio_hang_token_phien ON gio_hang(token_phien);
CREATE INDEX idx_chi_tiet_gio_hang_ma_gio_hang ON chi_tiet_gio_hang(ma_gio_hang);
CREATE INDEX idx_chi_tiet_gio_hang_ma_bien_the ON chi_tiet_gio_hang(ma_bien_the);
CREATE INDEX idx_topping_gio_hang_ma_chi_tiet_gio ON topping_gio_hang(ma_chi_tiet_gio);
CREATE INDEX idx_topping_gio_hang_ma_topping ON topping_gio_hang(ma_topping);
CREATE INDEX idx_kmsp_ma_chuong_trinh ON khuyen_mai_san_pham(ma_chuong_trinh);
CREATE INDEX idx_kmsp_ma_san_pham ON khuyen_mai_san_pham(ma_san_pham);
CREATE INDEX idx_kmsp_ma_danh_muc ON khuyen_mai_san_pham(ma_danh_muc);
CREATE INDEX idx_kmhd_ma_chuong_trinh ON khuyen_mai_hoa_don(ma_chuong_trinh);
CREATE INDEX idx_kmv_ma_chuong_trinh ON khuyen_mai_voucher(ma_chuong_trinh);
CREATE INDEX idx_don_hang_ma_ca ON don_hang(ma_ca);
CREATE INDEX idx_don_hang_ma_thu_ngan ON don_hang(ma_thu_ngan);
CREATE INDEX idx_don_hang_ma_khach_hang ON don_hang(ma_khach_hang);
CREATE INDEX idx_don_hang_ma_ban ON don_hang(ma_ban);
CREATE INDEX idx_don_hang_ma_voucher ON don_hang(ma_voucher);
CREATE INDEX idx_don_hang_trang_thai_ngay_tao ON don_hang(trang_thai, ngay_tao);
CREATE INDEX idx_don_hang_kenh_dat_hang_ngay_tao ON don_hang(kenh_dat_hang, ngay_tao);
CREATE INDEX idx_chi_tiet_don_hang_ma_don_hang ON chi_tiet_don_hang(ma_don_hang);
CREATE INDEX idx_chi_tiet_don_hang_ma_bien_the ON chi_tiet_don_hang(ma_bien_the);
CREATE INDEX idx_topping_don_hang_ma_chi_tiet_don ON topping_don_hang(ma_chi_tiet_don);
CREATE INDEX idx_topping_don_hang_ma_topping ON topping_don_hang(ma_topping);
CREATE INDEX idx_giao_dich_thanh_toan_ma_don_hang_trang_thai ON giao_dich_thanh_toan(ma_don_hang, trang_thai);
CREATE INDEX idx_phieu_nhap_hang_ma_nha_cung_cap ON phieu_nhap_hang(ma_nha_cung_cap);
CREATE INDEX idx_phieu_nhap_hang_ma_nguoi_nhap ON phieu_nhap_hang(ma_nguoi_nhap);
CREATE INDEX idx_chi_tiet_phieu_nhap_ma_phieu_nhap ON chi_tiet_phieu_nhap(ma_phieu_nhap);
CREATE INDEX idx_chi_tiet_phieu_nhap_ma_bien_the ON chi_tiet_phieu_nhap(ma_bien_the);
CREATE INDEX idx_chi_tiet_phieu_nhap_ma_topping ON chi_tiet_phieu_nhap(ma_topping);
